const { Return } = require("../models");

const returnData = [
  {
    id: 1,
    part_number: "S8EEOO6Y",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 4,
    stock_corrected: true,
    reason_id: 1,
    condition_id: 2,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 1,
    status: "blue",
  },
  {
    id: 2,
    part_number: "9EDJUCA0",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 4,
    stock_corrected: true,
    reason_id: 2,
    condition_id: 1,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 5,
    status: "blue",
  },
  {
    id: 3,
    part_number: "H4NXH511",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 3,
    stock_corrected: true,
    reason_id: 3,
    condition_id: 7,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 2,
    status: "blue",
  },
  {
    id: 4,
    part_number: "KHQ57TRR",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 6,
    stock_corrected: true,
    reason_id: 4,
    condition_id: 4,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 6,
    status: "blue",
  },
  {
    id: 5,
    part_number: "Y2XSLVAZ",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 12,
    stock_corrected: true,
    reason_id: 5,
    condition_id: 1,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 1,
    status: "blue",
  },
  {
    id: 6,
    part_number: "J5463PR5",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 3,
    stock_corrected: null,
    reason_id: 3,
    condition_id: 5,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: true,
    action_id: 2,
    status: "red",
  },
  {
    id: 7,
    part_number: "1FQNF0D4",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 56,
    stock_corrected: null,
    reason_id: 4,
    condition_id: 8,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: true,
    action_id: 5,
    status: "red",
  },
  {
    id: 8,
    part_number: "1BXDNNM6",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: true,
    reason_id: 2,
    condition_id: 1,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "blue",
  },
  {
    id: 9,
    part_number: "7NCFQM3F",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 23,
    stock_corrected: null,
    reason_id: 6,
    condition_id: 6,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: true,
    action_id: 4,
    status: "red",
  },
  {
    id: 10,
    part_number: "NOJOHG70",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: 5,
    stock_corrected: null,
    reason_id: 4,
    condition_id: 3,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: true,
    action_id: 6,
    status: "red",
  },
  {
    id: 11,
    part_number: "01G2LM9I",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 2,
    condition_id: 2,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 1,
    status: "green",
  },
  {
    id: 12,
    part_number: "2CTKT35U",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 1,
    condition_id: 7,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 3,
    status: "green",
  },
  {
    id: 13,
    part_number: "4H6BDLAL",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 5,
    condition_id: 2,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 5,
    status: "green",
  },
  {
    id: 14,
    part_number: "ML1INNHG",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 3,
    condition_id: 4,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 2,
    status: "green",
  },
  {
    id: 15,
    part_number: "O9TI0VKE",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 2,
    condition_id: 2,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 1,
    status: "green",
  },
  {
    id: 16,
    part_number: "9HVTHKC9",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 4,
    condition_id: 3,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note | Office Notes - This is a test note",
    credit: true,
    action_id: 6,
    status: "green",
  },
  {
    id: 17,
    part_number: "4P2UWQ6X",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 3,
    condition_id: 4,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "teal",
  },
  {
    id: 18,
    part_number: "LFQEC9E8",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 1,
    condition_id: 7,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "teal",
  },
  {
    id: 19,
    part_number: "V2PUAB4K",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 1,
    condition_id: 1,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "teal",
  },
  {
    id: 20,
    part_number: "FPD95N2Q",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 2,
    condition_id: 2,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "teal",
  },
  {
    id: 21,
    part_number: "NC7HRYP6",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 5,
    condition_id: 1,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes:
      "Customer Notes - This is a test note | Warehouse Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "teal",
  },
  {
    id: 22,
    part_number: "WK6BB7R2",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 6,
    condition_id: null,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes: "Customer Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "yellow",
  },
  {
    id: 23,
    part_number: "8EP4ZCCS",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 2,
    condition_id: null,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes: "Customer Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "yellow",
  },
  {
    id: 24,
    part_number: "1TKO3NMS",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 1,
    condition_id: null,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes: "Customer Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "yellow",
  },
  {
    id: 25,
    part_number: "7NYC1OP4",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 1,
    condition_id: null,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes: "Customer Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "yellow",
  },
  {
    id: 26,
    part_number: "D72ZG19P",
    quantity: 1,
    request_date: "2022-02-12",
    current_stock: null,
    stock_corrected: null,
    reason_id: 2,
    condition_id: null,
    customer_name: "Test Company",
    customer_address: "123 Fake St.",
    customer_phone: "801-123-4567",
    customer_email: "email@email.com",
    notes: "Customer Notes - This is a test note",
    credit: null,
    action_id: null,
    status: "yellow",
  },
];

const seedReturns = () => Return.bulkCreate(returnData);

module.exports = seedReturns;
